* Being the Best at Your Work

I'm back home for reading week, so it's been nice to spend time with loved ones. Throughout this time, I've had some conversations with friends and family about various things. A particularly interesting one started off as how most interesting conversations do; with dreams of being at big tech. We talked about how great it would be to break into faang or mango or whatever you wish to call it, and all the benefits living in SF would bring. I then told him about some recent news regarding high achievers in tech getting paid obscene amounts for the sole pourpose of them not going to competitors. I mean imagine how good you must be at what you do to be paid not to even work but to prevent competitors from hiring you to work for them. This was motivating in a way. Being a top performer in your work would ofcourse bring high salary and employability but also intangible things as well. If you do well at your work, then people would come to you for help, which presents a great opportunity to improve as a leader and mentor, and help others.

This reminds me of what Naval Ravikant said about being an alpha male. The phrase does have a negative connotation, but I do think he means it in a different way. He says that having high potential is great, but many don't realize this potential. The ones that do offer many great things to the world, as they take care of not only themselves but people around them. It truly is hard to find non-lazy people, which makes them that much more valuable. In a way it's never been easier to distinguish oneself from the rest, but also never been more difficult. Here's what I mean; with technology, we have so many people that waste hours and days away, so not many are being very productive at all, so even the tiny bit of effort you bring the table is able to differentiate yourself. However, the people that do take their time to improve and exert this effort have exponentially increased the value of their effort with the use of tech in a productive way. Therefore, the bar has been raised to a higher level for high achievers.

Well, what can we do? I am currently navigating through it myself, but what I've deduced so far is this: The ones that thrive manage to control their attention and direct it to things they wish to achieve, while avoiding the many distractions that steal their attention away. Either they strengthened their willpower to say no to distractions, or they have designed their environment in such a way that it is incredibly hard for them to access these distractions. You can reflect on which one you prefer on your own, but they both work in their own way.  the sooner we are able to control our attention, the better.

Feel free to shoot me a message if you have any thoughts: yavuzselimafacan@gmail.com
