* My Favorite Word These Days

Dividends. That's the word. I only feel that I've earned the right to use it when I truly made a great decision. It deems that aciton a wise one somehow. The reason behind it I think is because it's ususally associated with farsighted investments. Responsible, well managed and thought out decisions that yield rewards of a long term plan. Maybe the reason it's my favorite right now is because it's something I seek. Perhaps I do need to make a few right long term decisions to get my life together. I do think it takes Just(my lowercase J is broken on emacs) a few consecutive good days to get back on track. I Just need a bit of momentum.

Slacking off lectures has not done me much good so I've decided to go to lectures. It'll suck at first but sticking to it feels like my only option to come out the other side this semester. A friend told me right before I left for Hamilton that I Just need to feel like I belong, and that the only way to do that is to go to campus as much as possible. She's right. It'll pay dividends.
