* Reading Week

To write this at 4:26am on a Saturday portrays a lot about my habits. I feel my eyes pushing through the struggle of staying open as my fingers fly across the keyboard. My torso on the bed while my knees are bent to provide support the laptop that delicately balances between my stomach and thighs.

It's been a long September and now I feel the calmness wash over me as a month of school is left behind and an eager set of midterms waiting on the other side of this reading week. It's always the same story; you say you'll study this time, that you have to catch up on lectures but nevertheless it's Thursday and you barely did any work so you cram away until Sunday and feel the anxiety that unpreparedness brings wash over you. What's different this time? I don't want to lie away and persuade you and me that I'm a changed man and I've reformed from my past actions. But to come back to me writing this at such a time once again demonstrates how false that would be. Promises were not kept, I still struggle to keep up with lectures after missing one because I feel behind and don't want to go to a lecture that I know I would not understand even though not going makes it worse and now it's 2 lectures behind and it snowballs into an entire semester of lectures unattended, gone in the blink of an eye.

I feel a call to action and a desire to change when I reflect on previous actions as they happen but that emotion fades away as time goes by and now I can't feel the urge to push through and get my shit together. I fear this is becoming a reoccuring theme and becomes a bigger task to overcome and a stronger habit to break. I feel like I know the right path forward and the right things to do but it's so difficult to do them when it's much easier to scroll away and forget about the task or perform easier non-critical thinking tasks. This feels similar to vibecoding in a way as you don't go through the uncomfortable aspect of feeling lost and confused and pushing through the discomfort to then learn and improve and become a better programmer. Instead you copy and paste and voila your problem is solved and your code works. But at what cost? As I postpone and push away those tasks they seem bigger and more difficult overtime and they become harder to tackle and most never get done after that.

I do want to sleep earlier and wake up at a reasonable time to eat breakfast in a relaxed manner and go to lecture without rushing or negotiating with myself that I'm too late and that it's not worth it to go after missing the first 10 minutes and whatnot. Then it's a chain of missed days and weeks and months. This week off feels like a blessing in that it's a soft restart where I can catch up and go to lectures without feeling behind and not feeling stressed the fuck out about midterms that I postpone and procrastinate studying Just to build up that anxiety enough to move my ass but it's too late by then and I'm not satisfied with my grade and I know what I have to do to avoid but can't get myself to do it and it's a loop.

I don't know what's different this time. But I know something has to change.

- Y.S.A
